[package]
name = "arcon_state"
version = "0.1.1"
authors = ["Miko≈Çaj Robakowski <mikolajr@kth.se>"]
edition = "2018"
readme = "README.md"
license = "AGPL-3.0-only"
repository = "https://github.com/cda-group/arcon"
homepage = "https://github.com/cda-group/arcon"
description = """
State management features for Arcon
"""

[features]
default = []
rocks = ["rocksdb"]
faster = ["faster-rs", "serde"]
metrics = []
sled_checkpoints = ["sled"]

[dependencies]
prost = "0.6"
bytes = "0.5"
snafu = "0.6"
custom_debug = "0.4"
smallbox = { version = "0.8", features = ["coerce"] }
tempfile = "3.1"
once_cell = "1.3"

serde = { version = "1.0", features = ["serde_derive"], optional = true }
rocksdb = { git = "https://github.com/mrobakowski/rust-rocksdb.git", branch = "arcon", optional = true } # TODO
sled = { git = "https://github.com/mrobakowski/sled.git", optional = true } # TODO
faster-rs = { version = "0.10", optional = true }
