[package]
name = "arcon_build"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
repository = "https://github.com/cda-group/arcon"
edition = "2018"

[features]
arcon_serde = []
unsafe_flight = []

[dependencies]
prost-build = "0.6"
